apiVersion: apps/v1
kind: Deployment
metadata:
  name: du-workload-bu-{{.Replica}}
  annotations:
    # Disable CPU balance with CRIO
    irq-load-balancing.crio.io: "disable"
    cpu-load-balancing.crio.io: "disable"
    cpu-quota.crio.io: "disable"
  labels:
    group: load
    svc: du-workload-bu-{{.Replica}}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: du-workload-bu-{{.Replica}}
  template:
    metadata:
      labels:
        group: load
        name: du-workload-bu-{{.Replica}}
    spec:
      runtimeClassName: performance-openshift-node-performance-profile
      containers:
        - image: "{{ .registry }}:5000/ran-test/fedora-stress-ng:master"
          imagePullPolicy: Always
          name: du-workload-bu-{{.Replica}}
          # Request and Limits must be identical for the Pod to be assigned to the QoS Guarantee
          resources:
            requests:
              cpu: 1000m
              memory: 1024M
            limits:
              cpu: 2000m
              memory: 2048M
          # securityContext:
          #   privileged: true
          env:
            - name: stress_cpu
              value: "1"
            - name: stress_vm
              value: "1"
            - name: stress_vm-bytes
              value: "512M"
            - name: stress_hdd
              value: "1"
            - name: stress_hdd-bytes
              value: "25"
          volumeMounts:
            - name: pvc-storage
              mountPath: /mnt/pvc-data
      dnsPolicy: Default
      terminationGracePeriodSeconds: 1
      # Add not-ready/unreachable tolerations for 15 minutes so that node
      # failure doesn't trigger pod deletion.
      tolerations:
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 900
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 900
      volumes:
        - name: pvc-storage
          persistentVolumeClaim:
            claimName: pvc-claim-20gb-{{.Replica}}